# Generated by Django 3.0.4 on 2020-03-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placename', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('summary', models.CharField(max_length=50)),
                ('rainProb', models.CharField(max_length=5)),
                ('temperature', models.CharField(max_length=5)),
                ('appTemperature', models.CharField(max_length=5)),
                ('uvindex', models.CharField(max_length=5)),
                ('icon', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hour24Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placename', models.CharField(max_length=30)),
                ('mainsummary', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=30)),
                ('summary', models.CharField(max_length=50)),
                ('rainProb', models.CharField(max_length=5)),
                ('temperature', models.CharField(max_length=5)),
                ('appTemperature', models.CharField(max_length=5)),
                ('uvindex', models.CharField(max_length=5)),
                ('icon', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placename', models.CharField(max_length=30)),
                ('mainsummary', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=30)),
                ('summary', models.CharField(max_length=50)),
                ('rainProb', models.CharField(max_length=5)),
                ('temperatureLow', models.CharField(max_length=10)),
                ('appTemperatureHigh', models.CharField(max_length=10)),
                ('temperatureHigh', models.CharField(max_length=10)),
                ('appTemperatureLow', models.CharField(max_length=10)),
                ('icon', models.CharField(max_length=30)),
            ],
        ),
    ]
